const { PDFParse } = require('pdf-parse')

/**
 * Extracts raw text from a PDF buffer. Returns the full text blob —
 * bank-specific parsers are responsible for splitting it into lines
 * and finding transaction rows.
 *
 * Note: this only works for "digital" PDFs where text is selectable.
 * Scanned/image-based statements will return empty or garbled text —
 * that requires OCR, which is explicitly deferred past Sprint 1
 * (see Sprint plan: "Start with digital PDFs only. Add OCR later.")
 *
 * Using pdf-parse v2's class-based API (`PDFParse` + `getText()`).
 * v1's simpler `pdfParse(buffer)` function call is NOT used here — it
 * failed to read PDFs generated by current pdfkit versions during
 * testing ("bad XRef entry"), since v1 is no longer maintained.
 */
async function extractTextFromPDF(buffer) {
  const parser = new PDFParse({ data: new Uint8Array(buffer) })
  const result = await parser.getText()
  return result.text
}

module.exports = { extractTextFromPDF }
